cmake_minimum_required(VERSION 3.15)
project(safe_math LANGUAGES CXX)

include(GNUInstallDirs)

add_library(SMath SHARED
	${CMAKE_CURRENT_SOURCE_DIR}/src/SMath.cpp)
set_target_properties(SMath PROPERTIES PUBLIC_HEADER ${CMAKE_CURRENT_SOURCE_DIR}/include/SMath.h)
target_include_directories(SMath PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)

add_library(SExp SHARED
	${CMAKE_CURRENT_SOURCE_DIR}/src/SExp.cpp)
set_target_properties(SExp PROPERTIES PUBLIC_HEADER ${CMAKE_CURRENT_SOURCE_DIR}/include/SExp.h)
target_include_directories(SExp PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)

install(TARGETS SMath
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT core 
	PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} COMPONENT core
	)

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/include/SResult.h
	DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} COMPONENT core)

install(TARGETS SExp
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT exp 
	PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} COMPONENT exp
	)
